dist: trusty

language: node_js

node_js:
  - "6"

before_install:
  - curl -sSL https://raw.githubusercontent.com/cljs-oss/canary/master/scripts/install-canary.sh | bash

install:
  - curl -O https://download.clojure.org/install/linux-install-1.9.0.273.sh
  - chmod +x linux-install-1.9.0.273.sh
  - sudo ./linux-install-1.9.0.273.sh

script:
  - script/test-pre
  - if [ -z $PARTITION_FILTER ] || [ $PARTITION_FILTER = "1" ]; then script/test-part 1; fi
  - if [ -z $PARTITION_FILTER ] || [ $PARTITION_FILTER = "2" ]; then script/test-part 2; fi
  - if [ -z $PARTITION_FILTER ] || [ $PARTITION_FILTER = "3" ]; then script/test-part 3; fi
  - if [ -z $PARTITION_FILTER ] || [ $PARTITION_FILTER = "4" ]; then script/test-part 4; fi
  - if [ -z $PARTITION_FILTER ] || [ $PARTITION_FILTER = "5" ]; then script/test-part 5; fi
  - if [ -z $PARTITION_FILTER ] || [ $PARTITION_FILTER = "6" ]; then script/test-part 6; fi
  - if [ -z $PARTITION_FILTER ] || [ $PARTITION_FILTER = "7" ]; then script/test-part 7; fi
  - if [ -z $PARTITION_FILTER ] || [ $PARTITION_FILTER = "8" ]; then script/test-part 8; fi
  - if [ -z $PARTITION_FILTER ] || [ $PARTITION_FILTER = "9" ]; then script/test-part 9; fi
  - if [ -z $PARTITION_FILTER ] || [ $PARTITION_FILTER = "10" ]; then script/test-part 10; fi
  - script/test-post
