dist: trusty

language: node_js

node_js:
  - "6"

before_install:
  - curl -sSL https://raw.githubusercontent.com/cljs-oss/canary/master/scripts/install-canary.sh | bash

install:
  - curl -O https://download.clojure.org/install/linux-install-1.9.0.273.sh
  - chmod +x linux-install-1.9.0.273.sh
  - sudo ./linux-install-1.9.0.273.sh

script:
  - script/test-pre
  - script/test-part 1
  - script/test-part 2
  - script/test-part 3
  - script/test-part 4
  - script/test-part 5
  - script/test-part 6
  - script/test-part 7
  - script/test-part 8
  - script/test-part 9
  - script/test-part 10
  - script/test-post
